name: flappy-bird
version: 1.0.0
description: a multiplayer flappy bird game
main: index.js
scripts:
  test: echo "Error: no test specified" && exit 1
repository:
  type: git
  url: git+https://github.com/rinojames007/flappy-bird.git
author: rino james
license: MIT
bugs:
  url: https://github.com/rinojames007/flappy-bird/issues
homepage: https://github.com/rinojames007/flappy-bird#readme
dependencies:
  typescript: "^5.1.3"
